# Generated by Django 3.1.5 on 2021-01-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='fflights',
            new_name='flights',
        ),
    ]
